services:
    db:
        container_name: db_postgres
        image: postgres:17.2-alpine
        ports:
            - "5432:5432"
        volumes:
            -   db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: app_publication_annonce
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

volumes:
    db_data: