name: Java CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Docker version
              run: |
                  docker --version
                  docker compose --version

            - name: Run docker compose
              run: docker compose up -d

            - name: Build and test
              run: |
                  mvn clean install

            - name: run tests
              run: mvn test

            - name: Clean
              if: always()
              run: docker compose down